---
resources:
- name: resource_from_git
  type: git
  source:
    uri: https://github.com/dignajar/concourse-test.git

jobs:
- name: job_helloworld
  public: true
  plan:
  - get: resource_from_git
    trigger: true
  - task: task_helloworld
    file: resource_from_git/tasks/helloworld/task.yml

